### PR TITLE
Implement Tooltip

### PR DESCRIPTION
**Pull request by maria-ericsson**
Signed-off-by: maria-ericsson <maria.chowdhury@ericsson.com>

### CODE REVIEW

**Comment by mirsky-work** [comment]
tooltips

Nice, but there are some issues that are demonstrated in the attached Gif taken from Gitpod:
- The tooltip seems to open up at a fixed position relative to the state, and not where the cursor is.
- It doesn't disappear when the cursor is moved. It does disappear when moving away from the chart.

Not an issue, but rather a question - what would it take to make the tooltip text "copyable", as it's already "selectable"?

**Comment by maria-ericsson** [comment]
> tooltips
> 
> Nice, but there are some issues that are demonstrated in the attached Gif taken from Gitpod:
- Thank you. 
> * The tooltip seems to open up at a fixed position relative to the state, and not where the cursor is.
- Tooltip position is updated.
> * It doesn't disappear when the cursor is moved. It does disappear when moving away from the chart.
> 
> Not an issue, but rather a question - what would it take to make the tooltip text "copyable", as it's already "selectable"?

Tooltip disappears 

- When the mouse leaves the chart

- Between selection of two state elements. There are two reasons for that

1. If tooltip contains html links, then the user should be able to click link to open the relevant web-page
2. Tooltip content should be copyable

**Comment by maria-ericsson** [comment]
> > tooltips
> > Nice, but there are some issues that are demonstrated in the attached Gif taken from Gitpod:
> 
> * Thank you.
> 
> > * The tooltip seems to open up at a fixed position relative to the state, and not where the cursor is.
> 
> * Tooltip position is fixed for a specific state element.
> * Tooltip position changes when a different state element is selected.
> 
> > * It doesn't disappear when the cursor is moved. It does disappear when moving away from the chart.
> > 
> > Not an issue, but rather a question - what would it take to make the tooltip text "copyable", as it's already "selectable"?
> 
> Tooltip disappears
> 
> * When the mouse leaves the chart
> * Between selection of two state elements. There are two reasons for that
> 
> 1. If tooltip contains html links, then the user should be able to click link to open the relevant web-page
> 2. Tooltip content should be copyable

--- tooltip close operation is added with a timer. 
---The tooltip content is copy-able and any URL that may be present in the tooltip is clickable. 
--- tooltip closes when the mouse leaves the timeline chart
--- tooltip closes when the mouse leaves the selected element.

**Comment by bhufmann** [comment]
Thanks. Feature implemented by #283.

**Pull request closed without merging**
