### PR TITLE
Update Gitpod live demo setup steps to README

### LINKED ISSUE #350: Update Gitpod live demo section in readme
Gitpod changed their branding so the screenshots and gif in the [live demo readme section](https://github.com/theia-ide/theia-trace-extension#try-a-live-demo-via-gitpod) should be updated to minimize user confusion. Also check if instructions should be updated.

### PR DESCRIPTION
**Pull request by IbrahimFradj**
Update Gitpod live demo and screenshots to minimize user confusion because Gitpod changed their branding.
 Fixes #350

I changed paths in ReadMe to my branch to see the result and you can review 
**Before merging:** we should update media file paths to  theia-ide/theia-trace-extension and change the branch If-gitpodDemo to matser (https://raw.githubusercontent.com/theia-ide/theia-trace-extension/master/doc/images/gitpod-live-demo-setup.gif) 

**Here is the result**

image

Signed-off-by: Ibrahim Fradj <ibrahim.fradj@ericsson.com>

### CODE REVIEW

**Review by MatthewKhouzam — APPROVED** [review]
Light theme ftw!

**Review by ebugden — APPROVED** [review]
This is great! ☀️ 
* I enjoy that the gif of the process feels like a real person is completing the tasks (compared to impeccable lightning speed execution). It's reassuring for users.
* I like the yellow highlight that appears behind the cursor when you click. It's useful extra info.

**Comment by ebugden** [comment]
@IbrahimFradj Can you switch the paths to what they should be when merged so that it's ready to go?

**Comment by IbrahimFradj** [comment]
@ebugden  i changed the paths to what they should be when merged

**Review by ebugden — COMMENTED** [review]
@MatthewKhouzam When this is merged will the old files automatically be overwritten? The new images have identical file names to the old ones.

**Comment by bhufmann** [comment]
> @MatthewKhouzam When this is merged will the old files automatically be overwritten? The new images have identical file names to the old ones.

@ebugden @MatthewKhouzam @IbrahimFradj new versions of screenshots with the same file name used to be not updated on github pages. They are somehow cached on GitHub.. I did some research on the web and many people where complaining about that. Unfortunately I can't find any link at the moment for that. 

To avoid this issue, all the images that I've uploaded in doc/images directory have a number as suffix. When there is a new version I upload a new file with a new number, delete the old one and reference the new file in the readme.

I don't know if this is still an issue, but my approach for sure works.

**Comment by ebugden** [comment]
> **bhufmann:** New versions of screenshots with the same file name used to be not updated on github pages. 

Oh fun, thanks for the heads up! So @IbrahimFradj put a "-v2" in the media files and adjust the paths to match. You can check the [readme on your branch](https://github.com/IbrahimFradj/theia-trace-extension/tree/IF-gitpodDemo#readme) to make sure the problem is fixed and the images update.

> **bhufmann:** I don't know if this is still an issue

Just checked the readme on Ibrahim's branch for this PR and it shows the old images so this is still an issue:
image

**Comment by IbrahimFradj** [comment]
@ebugden  i changed the paths and the name of the media file. we can see the result in [readme on the branch](https://github.com/IbrahimFradj/theia-trace-extension/tree/IF-gitpodDemo).

**Review by MatthewKhouzam — DISMISSED** [review]

**Review by ebugden — CHANGES_REQUESTED** [review]
Looks good! Now that we confirmed the images update, the last change (🤞) would be to point to file paths to the trace extension master instead of your branch. 

Thank you for all the updates! I didn't expect there to be so much back and forth for a readme update 😀

**Comment by IbrahimFradj** [comment]
@ebugden with great pleasure. i changed the path of files to trace extension master

**Review by ebugden — APPROVED** [review]
Looks ready to merge! Thanks for the quick update.

**Review by MatthewKhouzam — APPROVED** [review]

**Pull request merged**
