### PR TITLE
TimeGraph Rows and States deselects when zooming in/out

### PR DESCRIPTION
**Pull request by muddana-satish**
Remove state selection

This logic is already handled in timeline-chart. And validating states with id is incorrect. Hence removed it from this file.

This PR is dependent on https://github.com/theia-ide/timeline-chart/pull/49

Signed-off-by: muddana-satish <satish.muddana@ericsson.com>

### CODE REVIEW

**Review by tahini — CHANGES_REQUESTED** [review]
Works well. Again please update the yarn.lock file when the timeline-chart patch is in.

**Comment by muddana-satish** [comment]
> Works well. Again please update the yarn.lock file when the timeline-chart patch is in.

I updated the yarn.lock file. Could you please review it now.

**Review by bhufmann — APPROVED** [review]
Looks good to me

**Review by tahini — APPROVED** [review]
Works well, thanks!

**Pull request merged**
