### PR TITLE
Add ability to remove trace sets from Trace Explorer

### LINKED ISSUE #336: Improve discoverability of removing traces from Opened Traces
For example, close box 'X' could appear on hover (right aligned). Currently, the "Remove" operation is in the right-click context menu which is less discoverable [#277 (comment)](https://github.com/theia-ide/theia-trace-extension/issues/277#issuecomment-802157186).

image

----
Issue source: @ssmagula's user tests + brainstorming with TC and tool team members

### PR DESCRIPTION
**Pull request by hriday-panchasara**
Fixes #336 
Remove button appears on hover
Screen Shot 2021-10-26 at 4 18 01 PM

When window is made smaller the remove button would still appear
Screen Shot 2021-10-26 at 4 18 29 PM

Clicking on remove button deletes the trace, does the same as right-click->'Delete Trace'

### CODE REVIEW

**Comment by hriday-panchasara** [comment]
Tooltip added to remove button:
Screen Shot 2021-11-01 at 11 32 53 AM

**Review by bhufmann — DISMISSED** [review]
LGTM. Thanks for the contribution.

**Review by ebugden — CHANGES_REQUESTED** [review]
Requested change:
- [x] Button should be aligned with the trace group name (top right of the box). Otherwise when there are multiple files in the group it looks like you're deleting a particular file instead of all of them

image


----

🌈 Thank you for this improvement! These are great design choices:
- Having the button appear on hover keeps the widget visually clean and then draws attention to the button at a time the user might need it.
- @mirsky-work's suggestion to highlight the button when you hover directly over it clearly communicates that the user can interact with this button.

**Comment by ebugden** [comment]
> > Wondering what tooltip should we add to clarify that the buttons deletes an experiment and not the trace files. Perhaps something like "Delete Trace Set"? @ebugden, any thoughts?
> 
> Do we need to have a warning dialog box asking the user to confirm it?

Personally, I'm comfortable merging without a confirmation dialogue and waiting for user feedback on this. 
* I don't think the average user (my guess of an average user: ~1 GB traces, 1-2 traces opened together) would be bothered that there's no confirmation 
* But I think it's probable that users dealing with massive traces and complex analyses would want a confirmation box (ex. Because they don't want to accidentally lose all the analysis configuration work they've done, or because it takes a long time to complete analyses again).

**Comment by hriday-panchasara** [comment]
Remove button is aligned with trace group name:
Screen Shot 2021-11-03 at 10 30 41 AM

Added warning dialog box to confirm action:
remove-trace-button-gif

**Comment by ssmagula** [comment]
Is it correct that clicking this close-box merely removes the traces from the UI of the viewer? The user could add them again, if it were removed by mistake? If that's correct, then maybe the correct verb is "Remove traces from Trace Viewer"? I'd lean away from confirming a non-destructive action, but it's a bit of a judgement call.

**Comment by hriday-panchasara** [comment]
Screen Shot 2021-11-03 at 11 51 42 PM

**Comment by bhufmann** [comment]
> Is it correct that clicking this close-box merely removes the traces from the UI of the viewer? The user could add them again, if it were removed by mistake? If that's correct, then maybe the correct verb is "Remove traces from Trace Viewer"? I'd lean away from confirming a non-destructive action, but it's a bit of a judgement call.

What it does it removes the traces from the trace viewer UI and from the trace server back-end. But, the actual traces files are not deleted from the local file system.

**Comment by hriday-panchasara** [comment]
> Requested change:
> 
> * [ ]  Button should be aligned with the trace group name (top right of the box). Otherwise when there are multiple files in the group it looks like you're deleting a particular file instead of all of them
> 
> image
> 
> 🌈 Thank you for this improvement! These are great design choices:
> 
> * Having the button appear on hover keeps the widget visually clean and then draws attention to the button at a time the user might need it.
> * @mirsky-work's suggestion to highlight the button when you hover directly over it clearly communicates that the user can interact with this button.

I've implemented the requested changes as well as added a warning dialog box to confirm delete action

**Review by ebugden — CHANGES_REQUESTED** [review]
Requested changes:
- [x] The tooltip label ("Delete trace from trace viewer") and confirmation messages ("Remove traces from trace viewer") should be the same (since they refer to the same action). 

Thanks for the update!

**Comment by ebugden** [comment]
Something related to this PR is that the right-click context menu currently lists this same "Remove Trace from Trace Viewer" action as "Delete Trace". For consistency. This context menu should be changed to match the tooltip and confirmation "Remove Trace", but that has to do with #277 and would be a separate PR (I added a comment in that issue).

Context menu label for the same action as this PR: "Delete Trace"
image

----

> > Is it correct that clicking this close-box merely removes the traces from the UI of the viewer? The user could add them again, if it were removed by mistake? If that's correct, then maybe the correct verb is "Remove traces from Trace Viewer"? I'd lean away from confirming a non-destructive action, but it's a bit of a judgement call.
> 
> What it does it removes the traces from the trace viewer UI and from the trace server back-end. But, the actual traces files are not deleted from the local file system.

@ssmagula Removing the traces from the viewer is not entirely without consequence because you lose the analysis layout/configuration and also I believe all the analyses and indexing would need to be re-run which for large traces could be time consuming.

**Comment by hriday-panchasara** [comment]
> Requested changes:
> 
> * [ ]  The tooltip label ("Delete trace from trace viewer") and confirmation messages ("Remove traces from trace viewer") should be the same (since they refer to the same action).
> 
> Thanks for the update!

Screen Shot 2021-11-10 at 12 45 08 PM

**Review by ebugden — APPROVED** [review]
Thanks for the update! Looks good to me 🚀

**Comment by ebugden** [comment]
Before merging, please squash (combine) some of your commits. This PR doesn't need to be 8 commits.

**Review by ebugden — COMMENTED** [review]
I'll let someone else take a look at the code, but the visual result and the commit looks good to me! Thanks for this improvement @hriday-panchasara ☀️

**Comment by ssmagula** [comment]
Thanks, all for clarifying. I grasp the main issues, now. 

Short term: Let's change the labeling in the UI
from "Opened Traces" to » "Trace Sets"

This will enable the UI to use "Remove Trace Set" (on hover of close-box, and on right-click) to refer to the action of getting rid of this element ("trace group" seems equally clear, and we need to formalize our nomenclature, see below). The word "delete" implies "destruction that is non-recoverable." When a user gets rid of a trace set, the user will lose the indexing and any config, but this can be _redone_ so in my opionion, that's still a recoverable action. My gut is that confirming a recoverable action is not needed. But I'll defer to those who better know the pain of losing a giant trace set.

This discussion is a great example of why crystal clear nomenclature is _vital_. We (the product development team) use the word "Traces" to refer to both "a single trace data file" _and_ "a group or set of trace data files, which have already been indexed, and may already be configured by the user" 

**How might we even further clarify these nouns to the user?** If we are finding it hard to refer to these core nouns in a non-ambiguous way, how will users feel in the product? 
- Recommended: 
- A single trace file should have an icon and label that communicates "a single trace data file"
- A group of "trace data files" should similarly have a label and an icon that communicate "multiple trace data files" Maybe an acronym representing the trace format is also useful info to help disambiguate this set vs. that set?
- If people agree, I can write the user story for this

**Comment by ebugden** [comment]
Thank you for weighing in on this topic @ssmagula!

> **ssmagula:** Short term: **Let's change the labeling in the UI from "Opened Traces" to » "Trace Sets"**
>
> This will enable the UI to use "Remove Trace Set" (on hover of close-box, and on right-click) to refer to the action of getting rid of this element ("trace group" seems equally clear, and we need to formalize our nomenclature, see below). 

I can see how changing the widget label from "Opened Traces" to "Trace Sets" would clarify some things, but this change should be proposed and debated in a separate issue and it is out of the scope of this PR in my opinion. **Can you create a separate issue for this and we can discuss there?**

In the mean time I changed this PR's title to more accurately reflect the changes that are proposed here. (We can use the language "trace set" in the commit log even if it's not yet in the UI because on the implementation side of things it's relevant to make the distinction between a "trace" and a "trace set"/"trace group" (formerly "experiment"))

----

> **ssmagula:** The word "delete" implies "destruction that is non-recoverable." When a user gets rid of a trace set, the user will lose the indexing and any config, but this can be _redone_ so in my opionion, that's still a recoverable action. My gut is that confirming a recoverable action is not needed. But I'll defer to those who better know the pain of losing a giant trace set.

This PR already lave this action as "Removing a trace". I agree that "delete" shouldn't be used to describe this action (unrelated to this PR: this needs to be changed in the right-click context menu, see my [comment](https://github.com/theia-ide/theia-trace-extension/issues/277#issuecomment-964266704) on #277)

----

> **ssmagula:** This discussion is a great example of why **crystal clear nomenclature is _vital_.** We (the product development team) use the word "Traces" to refer to both "a single trace data file" _and_ "a group or set of trace data files, which have already been indexed, and may already be configured by the user"
> 
> **How might we even further clarify these nouns to the user?** If we are finding it hard to refer to these core nouns in a non-ambiguous way, how will users feel in the product?
> 
> * Recommended:
> * A single trace file should have an icon and label that communicates "a single trace data file"
> * A group of "trace data files" should similarly have a label and an icon that communicate "multiple trace data files" Maybe an acronym representing the trace format is also useful info to help disambiguate this file vs. that file?
> * If people agree, I can write the user story for this

**I agree that we should have a discussion about nomenclature, but again in a separate issue. Can you make a separate issue?**

One of the reasons this nomenclature discussion isn't totally obvious is that some trace formats (ex. CTF) are already a collection of several trace files (although you're never really looking at them individually?).

**Comment by mirsky-work** [comment]
Thanks everyone for the weighing in. I agree that _Remove_ is a better term than _Delete_, and the confirmation would probably be more annoying than useful, as it's a recoverable operation.

> * A single trace file should have an icon and label that communicates "a single trace data file"
> * A group of "trace data files" should similarly have a label and an icon that communicate "multiple trace data files" Maybe an acronym representing the trace format is also useful info to help disambiguate this file vs. that file?

@ssmagula, the distinction is already communicated today. Trace sets list the containing traces:
image

**Comment by ebugden** [comment]
> **mirsky-work:** I agree that [...] the confirmation would probably be more annoying than useful, as it's a recoverable operation.

Ok let's remove it then since several folks seem to agree. Not having a confirmation was my first reflex. @hriday-panchasara could you make this additional change?
- [ ] Remove confirmation box

----

> > * A single trace file should have an icon and label that communicates "a single trace data file"
> > * A group of "trace data files" should similarly have a label and an icon that communicate "multiple trace data files" Maybe an acronym representing the trace format is also useful info to help disambiguate this file vs. that file?
> 
> @ssmagula, the distinction is already communicated today. Trace sets list the containing traces: image

I made an issue #561 to continue the discussion about this. Left some thoughts there.

**Comment by bhufmann** [comment]
Just a quick note about the confirmation message. To avoid to show it all the time (and be annoying) there could be check-box `Don't show again` and the user's selection is then persisted. With this the users get informed about what happens and can choose to not see the warning again.

**Comment by ebugden** [comment]
My preference would be to merge this without a confirmation box. Then, if users mention that they're frustrated because they're accidentally deleting complex analysis setups we can add a confirmation box (maybe that shows only when the traces are large i.e. have a large number of events)

> **bhufmann:** To avoid to show it all the time (and be annoying) there could be a check-box `Don't show again` and the user's selection is then persisted. With this the users get informed about what is going to happen and can choose to see or to not see the warning again.

I think having a "Don't show again" checkbox makes more sense in a situation that involves risk (ex. "Are you sure you want to automatically connect to this network in the future"), but it this situation (removing a trace set) we think that in most cases there isn't significant risk associated with it (because for most trace sets it takes maybe a minute max to redo the all the analyses the user had open).

**Comment by hriday-panchasara** [comment]
> > **mirsky-work:** I agree that [...] the confirmation would probably be more annoying than useful, as it's a recoverable operation.
> 
> Ok let's remove it then since several folks seem to agree. Not having a confirmation was my first reflex. @hriday-panchasara could you make this additional change?
> 
> * [ ]  Remove confirmation box
> 
> > > * A single trace file should have an icon and label that communicates "a single trace data file"
> > > * A group of "trace data files" should similarly have a label and an icon that communicate "multiple trace data files" Maybe an acronym representing the trace format is also useful info to help disambiguate this file vs. that file?
> > 
> > 
> > @ssmagula, the distinction is already communicated today. Trace sets list the containing traces: image
> 
> I made an issue #561 to continue the discussion about this. Left some thoughts there.

I've removed the confirmation box

**Comment by ebugden** [comment]
The behaviour looks good to me! Thanks for the update.

**Review by bhufmann — APPROVED** [review]
It looks good to me. Thanks!

**Comment by bhufmann** [comment]
> My preference would be to merge this without a confirmation box. Then, if users mention that they're frustrated because they're accidentally deleting complex analysis setups we can add a confirmation box (maybe that shows only when the traces are large i.e. have a large number of events)
> 
> > **bhufmann:** To avoid to show it all the time (and be annoying) there could be a check-box `Don't show again` and the user's selection is then persisted. With this the users get informed about what is going to happen and can choose to see or to not see the warning again.
> 
> I think having a "Don't show again" checkbox makes more sense in a situation that involves risk (ex. "Are you sure you want to automatically connect to this network in the future"), but it this situation (removing a trace set) we think that in most cases there isn't significant risk associated with it (because for most trace sets it takes maybe a minute max to redo the all the analyses the user had open).

Removing a trace from the trace viewer will remove all analysis results and it can be a long procedure to rebuild (incl. upload the trace to the server in the future remote case). This depends on the size of the trace. I'll open a separate issue tracker for the confirmation dialog box because it's out of scope of this PR.

**Review by PatrickTasse — APPROVED** [review]
The button works but we will need to fix (later?) the inconsistency between the button tooltip and the equivalent item in the context menu. Also not sure about plural in "Remove traces" since the button applies to only one "Opened trace".

**Comment by bhufmann** [comment]
I'll going to merge it as because it brings in an UX improvement. The inconsistent labels can be fixed as part of fix for #277.

**Pull request merged**
