### PR TITLE
Add Gitpod live demo setup steps to README

### PR DESCRIPTION
**Pull request by ebugden**
Explain how to run the trace extension using Gitpod to help external users discover the demo. Related to #173.

Update: File paths now point to the official github, so the new media won't work in the README until this PR is merged.

~~See ebugden fork [README](https://github.com/ebugden/theia-trace-extension/tree/gitpod-demo-readme) for the intended visuals.~~

~~**Before merging:** Update media file paths to theia-ide/theia-trace-extension. File paths currently point to ebugden fork so media can be reviewed before merging.~~

Signed-off-by: ebugden <erica.bugden@gmail.com>

### CODE REVIEW

**Comment by MatthewKhouzam** [comment]
Hot damn! Could you upload the images to theia already? They can remain dormant until we merge this.

It really really good!

**Comment by MatthewKhouzam** [comment]
Wait, images are in git. Ok, so yeah, we will follow your suggestion :)

**Review by tahini — CHANGES_REQUESTED** [review]
Thanks for this contribution! Could you please update the paths to the images so we can easily merge this? Since we usually review by getting the branch, we can see the media even if the links does not work.

**Review by tahini — APPROVED** [review]
Thanks for the update!

**Review by marcdumais-work — CHANGES_REQUESTED** [review]
There's already a button you can click to open this repo in Gitpod. It's at the top of the README. I suggest you move it in your text block, and use something like "click on the Gitpod button below"
image

**Comment by marcdumais-work** [comment]
I could not easily see the images so I'll not comment on them. The text otherwise looks good!

**Comment by ebugden** [comment]
@marcdumais-work Updated! Was the goal to get rid of redundancy or because a button is more inviting to click than a link?

**Review by marcdumais-work — APPROVED** [review]
LGTM, thanks!

**Review by marcdumais-work — COMMENTED** [review]
Oh, I see the Gitpod button will be an image in this version? I would have kept the HTML button personally, but it's not a big thing, since you still have the link.

**Comment by ebugden** [comment]
> **@marcdumais-work:** I see the Gitpod button will be an image in this version

I just copy-pasted the button code that was in the file originally. Didn't adjust anything.

> **@marcdumais-work:** I would have kept the HTML button personally

There is still time! But I don't know what you mean by HTML button vs. Image button. Could you post code or give more details?

**Comment by marcdumais-work** [comment]
@ebugden : Everything is good on my side. Thanks for this PR!

**Comment by bhufmann** [comment]
Cool addition! Thanks

**Pull request merged**
