### PR TITLE
Table, Timegraph, XY Chart: Display "no results' message

### PR DESCRIPTION
**Pull request by ebugden**
when analysis results are empty.

For all components, display message in the main chart area to keep
visual consistency.

Other details:
* Make CSS class name general since it is being used for several messages
now.
* Change CSS properties to consider text displayed on multiple
lines. The manual margin-top ajustment is a hack that only works for
single line messages.

Generalization of PR theia-ide#447

Fixes theia-ide#406

Signed-off-by: Erica Bugden <erica.bugden@gmail.com>

### CODE REVIEW

**Comment by ebugden** [comment]
Let me know if I should squash these commits:
* Move "no results" message to parent class 
* Table, Timegraph, XY Chart: Display "no results"

**Review by bhufmann — DISMISSED** [review]
Looks good to me. Thanks for the contribution.

**Review by Rodrigoplp-work — DISMISSED** [review]

**Comment by ebugden** [comment]
I realized that I didn't add this message (or the analysis failed message) to the new data tree output component. Should I make a separate PR for that with both messages?

**Comment by bhufmann** [comment]
> I realized that I didn't add this message (or the analysis failed message) to the new data tree output component. Should I make a separate PR for that with both messages?

yes, please.

**Review by bhufmann — CHANGES_REQUESTED** [review]
@ebugden I did a rebase on github, but now it doesn't compile anymore :-( I'm still not used to github way of working. 

Could you please discard my rebase merge and rebase it manually in your environment, and  when adding the data tree change?

**Comment by ebugden** [comment]
> @ebugden I did a rebase on github, but now it doesn't compile anymore :-( I'm still not used to github way of working.
> 
> Could you please discard my merge commit and rebase it manually in your environment, and when adding the data tree change?

Yes I'll do that! (I don't think it's possible to rebase using the default github UI. I think you have to add a custom command? I always do it manually with the terminal.)

**Comment by ebugden** [comment]
Update:
* Rebase on master

----

Should be good to merge! I'll add the message for the data tree component in a separate PR. (Anyways I'm thinking of moving all the error message handling stuff to the abstract output component so we don't need to remember to copy in the checks when new output components are added.)

**Comment by bhufmann** [comment]
> > @ebugden I did a rebase on github, but now it doesn't compile anymore :-( I'm still not used to github way of working.
> > Could you please discard my merge commit and rebase it manually in your environment, and when adding the data tree change?
> 
> Yes I'll do that! (I don't think it's possible to rebase using the default github UI. I think you have to add a custom command? I always do it manually with the terminal.)

My own patches I do with the terminal too. For, other people's PRs I usually ask them to rebase. But today I thought I could rebase for you and merge it since it was fully approved. Anyways it's done.

**Review by bhufmann — APPROVED** [review]
Thanks for the rebase. It still looks good to me.

**Comment by bhufmann** [comment]
> > I realized that I didn't add this message (or the analysis failed message) to the new data tree output component. Should I make a separate PR for that with both messages?
> 
> yes, please.

I merged this one now. Just create a new PR for the data tree.

**Pull request merged**
