### PR TITLE
Allow events table search from the current selected row

### LINKED ISSUE #400: Events table search always start from the first row.
https://github.com/theia-ide/theia-trace-extension/pull/396#pullrequestreview-689757368

### PR DESCRIPTION
**Pull request by muddana-satish**
fixes #400

Signed-off-by: muddana-satish <satish.muddana@ericsson.com>

### CODE REVIEW

**Review by MatthewKhouzam — COMMENTED** [review]
This does what it should. But the commit message should be

"Allow events table search from the selected row" as you can move with the scrollbar and it still works well.

**Review by bhufmann — DISMISSED** [review]
I tested it and the UX seems good to me. 

When entering a search string, then matched strings in the visible rows are updated. When pressing enter, it goes to the next matching event (starting from the selected row) regardless if it's in the current cache or if it needs to fetch new data from the back-end).

Thanks for the improvement

**Review by PatrickTasse — DISMISSED** [review]

**Comment by muddana-satish** [comment]
> "Allow events table search from the selected row" as you can move with the scrollbar and it still works well.

It actually works even when no row is selected. :)

**Comment by muddana-satish** [comment]
Updated the commit message. Created #410 for regular expression searching.

**Comment by bhufmann** [comment]
> Updated the commit message. Created #410 for regular expression searching.

I actually like the initial commit message (and PR title) better than the new one. It's more obvious what the improvement is. 

Maybe only replace "visible" with "selected":
"Allow events table search from the current selected row"

**Review by bhufmann — APPROVED** [review]
Thanks!

**Review by PatrickTasse — APPROVED** [review]

**Pull request merged**
