### PR TITLE
Timegraph: Fixed issue #117 (undefined variable exception)

### PR DESCRIPTION
**Pull request by smouss**
Fixed undefined variable (timeGraphEntries) exception in tsp-data-provider.ts

Signed-off-by: soukaina <soukaina.moussaoui@polymtl.ca>

### CODE REVIEW

**Review by tahini — CHANGES_REQUESTED** [review]
I can't reproduce the problem, but seeing this patch, I'm pretty convinced this solves it! Thanks!

Just a little comment to re-order and refactor the if and else statements and it should be ok. Also, please cherry-pick your patch on master instead of merging the branches.

**Review by bhufmann — APPROVED** [review]
I was able to test it with a local changed trace server.

**Review by tahini — APPROVED** [review]
I'll approve, we can refactor later

**Comment by tahini** [comment]
I'll rebase the PR and push again. Thanks @smouss

**Pull request closed without merging**
