### PR TITLE
Update for rename of TimeGraphRowElement to TimeGraphStateComponent

### PR DESCRIPTION
**Pull request by PatrickTasse**
Signed-off-by: Patrick Tasse <patrick.tasse@ericsson.com>

### CODE REVIEW

**Review by bhufmann — DISMISSED** [review]
Looks good to me

**Review by MatthewKhouzam — CHANGES_REQUESTED** [review]
Looks like the resources view is broken, can you explain why?

**Comment by PatrickTasse** [comment]
> Looks like the resources view is broken, can you explain why?

Unrelated, it's an exception in arrows handling.

**Review by bhufmann — APPROVED** [review]
LGTM

**Review by MatthewKhouzam — APPROVED** [review]

**Pull request merged**
