### PR TITLE
Add tooltip support for timegraph states

### PR DESCRIPTION
**Pull request by PatrickTasse**
Signed-off-by: Patrick Tasse <patrick.tasse@ericsson.com>

### CODE REVIEW

**Review by MatthewKhouzam — APPROVED** [review]

**Review by MatthewKhouzam — COMMENTED** [review]
I am not approving because there is a bug I consider bad, but I am not requesting the change because even with this bug, the tooltips are so much better than before. I know you're aware of the bug as you showed it to me. :)

https://user-images.githubusercontent.com/419535/111499322-35b63d80-8719-11eb-8a20-ddf4cc240b43.mp4

**Comment by MatthewKhouzam** [comment]
I am looking at the code, see here.

https://user-images.githubusercontent.com/419535/111694654-89538480-8808-11eb-8f4c-6647f12ef160.mp4

This is pretty bad, the entry row changes too.

**Comment by MatthewKhouzam** [comment]
I think the Y axis is a little better.
https://user-images.githubusercontent.com/419535/111799571-8658a280-88a1-11eb-81e3-ec89106edf2f.mp4

**Comment by MatthewKhouzam** [comment]
HARD +2

**Review by bhufmann — APPROVED** [review]
Looks good to me. Thanks!

**Pull request merged**
