### PR TITLE
#60: Add github action to publish next version

### PR DESCRIPTION
**Pull request by bhufmann**
Signed-off-by: Bernd Hufmann <Bernd.Hufmann@ericsson.com>

### CODE REVIEW

**Comment by tahini** [comment]
What does this publish exactly, the viewer prototype? Are we ready for this? Is it mature enough yet? Or we go for release-early/release-often approach?

**Comment by bhufmann** [comment]
> What does this publish exactly, the viewer prototype? Are we ready for this? Is it mature enough yet? Or we go for release-early/release-often approach?

The publish will only publish the viewer prototype and not the electron nor the browser app. Electron/browser app are only examples to easily test during development. Applications (IDEs) should be deployed differently (for example under theia-apps).

The Github action added in this patch would publish a "next" version at every merged pull request in master. It's similar to nightly builds that are providing bleeding edge. I also added a command in the root package.json file for providing releases (latest), but it's not yet connected to a Github action. 

It's really for simplification. The reason having it as npm package is to be able to integrate it more easily into applications, like a Theia based IDE. Users can include in their IDE build to try. We were asked to provide an npm package for the trace extension. We already publish tsp-typescript-client (https://www.npmjs.com/package/tsp-typescript-client) and the timeline-chart (https://www.npmjs.com/package/timeline-chart) the same way as npm packages.

> Are we ready for this? Is it mature enough yet?
These are a good questions. Probably not. For sure not for releases. But it could be ok providing "next" versions. However, the name that it would be published as would be "trace viewer" and it's probably not the name that we'd like. Once published the package will be there basically forever.

We can hold of a bit with this PR, but sooner than later we need to think about the deployment so that it can be included in user's IDEs.

**Comment by tahini** [comment]
Do you have a need to publish this now for internal purposes? My main concern is that we're investigating if [part of] the trace viewer could be a vscode plugin, in which case, our publishing platform would change. I'd wait a bit for the investigation to go a little further before publishing anything since, as you put it, the package will be there basically forever...

I think we can have a sensible answer by september about vscode or not vscode. And if so, we can easily port everything that is there to a vscode plugin and publish there instead.

**Comment by bhufmann** [comment]
Yes, publishing as npm package would make it easier for our stakeholders, but could be useful for others as well that want to integrate with it. 

I agree that there are some unknowns regarding the platform and maybe it's better to hold off with this PR for now, until we know if we switch to a vscode plugin or not. I'll check for some alternatives for our stakeholders in meanwhile.

**Comment by tahini** [comment]
I'm just raising concerns here, but I don't want to stop progress or be an impediment to collaboration. If it's easier for you guys, we can go ahead with this patch. Just let me know if it's going to be used right now by your stakeholders, I'll positively review this patch. But if the timeline is a month or so, it could wait for more certainty.

**Comment by bhufmann** [comment]
> I'm just raising concerns here, but I don't want to stop progress or be an impediment to collaboration. If it's easier for you guys, we can go ahead with this patch. Just let me know if it's going to be used right now by your stakeholders, I'll positively review this patch. But if the timeline is a month or so, it could wait for more certainty.

These are valid concerns. I'll clarify on my side to see if we could wait with this until we have some more certainty.

**Pull request closed without merging**
