### PR TITLE
Add related projects diagram to Readme

### PR DESCRIPTION
**Pull request by ebugden**
[See result on merging branch.](https://github.com/ebugden/theia-trace-extension/tree/add-related-code-diagram#related-code)

If approved, before merging:
- [ ] Change image path to master in the main repo
- [ ] Include SVG so that if necessary edits can be made to the diagram 

----

Diagrams are effective at communicating structural information. Helping
devs understand how different related components of the project work
together reduces the onboarding effort for existing devs and helps new
devs get rolling more quickly.

Signed-off-by: Erica Bugden <erica.bugden@gmail.com>

Continuation of: #402 

----

Draft because:
* @bhufmann [mentioned](https://github.com/theia-ide/theia-trace-extension/pull/402#pullrequestreview-736389081) there were errors last time this was posted:
 > **bhufmann:** The diagram needs some updates, because it doesn't show the reality. For example, the Trace Compass version based on Eclipse, doesn't use the TSP and the Trace Server over REST API. The UI uses direct function calls to Trace Compass core APIs.
* This is definitely not server agnostic. (In fact the entire way the related code section is phrased is not server agnostic which could be improved)

### CODE REVIEW

**Comment by ebugden** [comment]
Current diagram: 

image

**Comment by bhufmann** [comment]
Just a reminder that the Trace Compass Eclipse version doesn't query the trace server using the TSP. It uses the same Java classes, but does direct function calls. There is still some coupling between Eclipse Trace Compass UI and core, even if they use the data provider concept. Some other UI components can't easily be replaced by the TSP driven data, e.g. events table or project explorer. The latter is fully differently implemented in Theia. Even if this would be desirable to have the Eclipse UI use the Trace Server and TSP, it would be a huge effort to implement that in the Eclipse Trace Compass UI. Right now the focus is to enhance and progress with the web-based client.

**Comment by mirsky-work** [comment]
I agree that such a diagram would be useful for new contributors. I'm not sure how often it'll have to be updated, but if we'd like to reserve the option for future updates, I suggest to look into using a PlantUML generated diagram, like described in that [SOF answer](https://stackoverflow.com/a/32771815).

**Comment by ebugden** [comment]
Thank you both for the feedback! 

> **bhufmann:** Just a reminder that the Trace Compass Eclipse version doesn't query the trace server using the TSP. It uses the same Java classes, but does direct function calls. There is still some coupling between Eclipse Trace Compass UI and core, even if they use the data provider concept.

I'm going to try a diagram version without Trace Compass. I don't think it worth making the diagram more complex to make the corrections for Trace Compass and removing it will also make the diagram more server agnostic.

----

> **mirsky-work:** I'm not sure how often it'll have to be updated, but if we'd like to reserve the option for future updates, I suggest to look into using a PlantUML generated diagram, like described in that [SOF answer](https://stackoverflow.com/a/32771815).

My goal is to keep this diagram extremely high level so it doesn't need to be updated except under extreme circumstances. For example, even if other pieces of code become separate libraries (in addition to the Timeline chart) I don't think those need to be added to the diagram. Showing the Timeline chart is just an example to show that some smaller pieces of the extension are in separate repos.

For this diagram, I can also provide the SVG (in addition to the PNG) so that edits could be made if necessary.

It could make sense to have an additional more complex diagram of components, but maybe it would need to be auto-generated for now? Unless main parts are pretty stable? If they're pretty stable I could start a more detailed diagram for you guys.

**Comment by ebugden** [comment]
Update:
* Remove Trace Compass 

image

**Comment by bhufmann** [comment]
In my [EclipseCon2021 presentation](https://www.eclipsecon.org/2021/sessions/trace-compass-cloud-eclipse-trace-compass%E2%80%99s-migration-towards-theia) I showed an architecture diagram (page 18) for Theia. It shows some more details on the architecture. Maybe it can be used for this PR (as-is or modified).

**Comment by ebugden** [comment]
> **bhufmann:** In my [EclipseCon2021 presentation](https://www.eclipsecon.org/2021/sessions/trace-compass-cloud-eclipse-trace-compass%E2%80%99s-migration-towards-theia) I showed an architecture diagram (page 18) for Theia. It shows some more details on the architecture. Maybe it can be used for this PR (as-is or modified).

My understanding of the EclipseCon diagram is that it includes components that are internal to the extension repo (ex. traceviewer-base, traceviewer-react-components). This is a higher level of detail than intended for this PR. There is a need for a more detailed diagram like the EclipseCon one, but this should be in a different readme section (ex. Architecture). We can have multiple diagrams at different levels of abstraction. 

The slide in question:
image

----

This PR is for a "External Related Code Diagram" rather than a "General Architecture" diagram. The diagram proposed in this PR is just intended to efficiently explain the other repos mentioned in the related code table (since structured information is easier to remember and understand) (see below for the diagram in context). So the components listed in this diagram are limited to the elements listed in the related code table. The consistent level of detail between the diagram and table makes it easier for readers to notice links between the table and the diagram. 

Unless there are related external repos that aren't mentioned in the related code table (these should be added), I wouldn't add additional components to this PR's diagram.

Context the related code diagram is presented in:
image

**Comment by ebugden** [comment]
Added a separate PR #587 with the more detailed architecture diagram.

**Comment by ebugden** [comment]
> **mirsky-work:** Would be nice to add the names of the repos of each of the components, e.g., Client-side Trace Server Protocol Implementation (tsp-typescript-client), and also perhaps mention that the TSP communication is via REST. Other than that it LGTM and would be helpful for new developers in the future, IMO.

Update:
* Add tsp-typescript-client repo name (except for this one, the other repo names are very similar to the labels used in the related code table)
* Mention that the TSP is RESTful
* Update related code table to match diagram and also include this additional information

Current diagram:
image

**Comment by ebugden** [comment]
@bhufmann @mirsky-work Is there still interest in this PR? I can leave it open and add the SVG file to the PR so that someone can continue working on the diagram if they want. Or I could close it. What is best?

**Comment by bhufmann** [comment]
> @bhufmann @mirsky-work Is there still interest in this PR? I can leave it open and add the SVG file to the PR so that someone can continue working on the diagram if they want. I could also close it. What is best?

Maybe the test update could be used. I don't think we need the diagram because the recently added architecture diagram shows pretty much the same information.

**Comment by ebugden** [comment]
> > **ebugden:** @bhufmann @mirsky-work Is there still interest in this PR? I can leave it open and add the SVG file to the PR so that someone can continue working on the diagram if they want. I could also close it. What is best?
> 
> **bhufmann:** Maybe the test update could be used. I don't think we need the diagram because the recently added architecture diagram shows pretty much the same information.

It's true that there's quite a bit of overlap between this and the more detailed architecture diagram. I'm comfortable with closing this PR!

I don't know what the "test update" is.

**Comment by bhufmann** [comment]
> > > **ebugden:** @bhufmann @mirsky-work Is there still interest in this PR? I can leave it open and add the SVG file to the PR so that someone can continue working on the diagram if they want. I could also close it. What is best?
> > 
> > 
> > **bhufmann:** Maybe the test update could be used. I don't think we need the diagram because the recently added architecture diagram shows pretty much the same information.
> 
> It's true that there's quite a bit of overlap between this and the more detailed architecture diagram. I'm comfortable with closing this PR!
> 
> I don't know what the "test update" is.

It was a typo. I meant "text update".

**Comment by ebugden** [comment]
> > > > **ebugden:** @bhufmann @mirsky-work Is there still interest in this PR? I can leave it open and add the SVG file to the PR so that someone can continue working on the diagram if they want. I could also close it. What is best?
> > > 
> > > 
> > > **bhufmann:** Maybe the test update could be used. I don't think we need the diagram because the recently added architecture diagram shows pretty much the same information.
> > 
> > 
> > **ebugden:** It's true that there's quite a bit of overlap between this and the more detailed architecture diagram. I'm comfortable with closing this PR!
> > I don't know what the "test update" is.
> 
> **bhufmann:** It was a typo. I meant "text update".

I think the text about this that is already in the readme is sufficient for now. I'll go ahead and close this PR.

**Pull request closed without merging**
