### PR TITLE
Refresh Open Traces View after server start

### LINKED ISSUE #601: Opened Traces view not refreshed after server start
When starting the trace server with `CTRL+SHIFT+P -> Start Trace Server`, the Opened Traces view is not refreshed. The theiatrace-viewer should refresh its views to show what is available on the server. Note that, right now it will be sufficient to fetch the list of experiments to populate the list of Opened Traces. However, a generic refresh should be implemented so that it's possible to refresh other server data in the future.

no-refresh-after-server-start

### PR DESCRIPTION
**Pull request by hriday-panchasara**
fixes #601

Signed-off-by: hriday-panchasara <hriday.panchasara@ericsson.com>

### CODE REVIEW

**Comment by hriday-panchasara** [comment]
> Thanks for fixing this. It works as expected. Some comment though.

@bhufmann Made the requested edits

**Review by bhufmann — APPROVED** [review]
Nice improvement. Thanks for fixing this!

**Review by Rodrigoplp-work — DISMISSED** [review]

**Comment by bhufmann** [comment]
@hriday-panchasara could you please rebase this PR so that we can merge it? There is currently a merge conflict. Thanks.

**Review by bhufmann — APPROVED** [review]
Looks still good after rebase. Thanks

**Pull request merged**
