### PR TITLE
Update Widget colors based on themes

### LINKED ISSUE #385: Flame Chart stays in theme it was created with
The Flame Chart doesn't switch themes. It stays in the theme it was created with.

https://user-images.githubusercontent.com/28311615/121206787-be3f0880-c846-11eb-989e-8fdae1cd9120.mp4

### PR DESCRIPTION
**Pull request by muddana-satish**
fixes #385

depends on https://github.com/theia-ide/timeline-chart/pull/143

Signed-off-by: muddana-satish <satish.muddana@ericsson.com>

### CODE REVIEW

**Comment by muddana-satish** [comment]
Kapture 2021-06-30 at 18 27 16

**Review by MatthewKhouzam — COMMENTED** [review]
the approach looks good, can you get timeline 143 merged then we see this vs reality?

**Review by bhufmann — CHANGES_REQUESTED** [review]
LGTM. Works well with the timeline-chart change. Please update the yarn.lock to include the latest timeline-chart version

**Comment by muddana-satish** [comment]
> LGTM. Works well with the timeline-chart change. Please update the yarn.lock to include the latest timeline-chart version

I updated the yarn.lock

**Review by bhufmann — APPROVED** [review]
Nice improvement. Looks good to me. Thanks.

**Review by PatrickTasse — APPROVED** [review]

**Pull request merged**
