### PR TITLE
Panelize trace explorer + other frontend fixes

### PR DESCRIPTION
**Pull request by kenneth-marut-work**
This MR applies several frontend fixes to the Trace Explorer Widget including:
- Wrap each 'sub widget' inside a panel layout to allow for view flexibility, drag/drop, expand/collapse, resize
- Address explorer-widget responsiveness, rows now adjust according to widget width (partially addresses #30)
- Add on-hover behavior to lists, and change to 'pointer' cursor
- Fix focus timeout issue when Trace Viewer widgets are activated, addresses #182 
- Fix double scrollbar from appearing in lists
- Fix some circular dependency issues
- Minor CSS fixes for consistency inside widget with Theia
- Refactoring of injection to use parameter style with postConstructor vs. constructor for extensibility, adjust `.bind` calls to Theia arrow function style
- Fixed duplicate registration of Open Trace command handler for file dialog and update command label to address #223 

Note that this is quite a large diff but most of the changes are due to copy/pasting into sub components and classes. I have not introduced any new functionality or removed existing functionality. Please verify for regressions.

Screenshot:

dynamic_rows

### CODE REVIEW

**Comment by danieltomasku** [comment]
Tested and looks good! This is a big improvement to the UI of the left panel. Nice work :clap:

**Comment by mirsky-work** [comment]
Verified on Gitpod. Very nice improvement, thanks for the contribution!

**Comment by MatthewKhouzam** [comment]
Hi Keneth, this looks really nice, but we have a minor UI niggle.

image

Please check out this image, it seems to add a scroll bar to experiments. It seems fine before the patch and problematic after. Could someone else confirm? The problem may exist between the reviewer's chair and keyboard though.

**Comment by danieltomasku** [comment]
> image

@MatthewKhouzam can you capture the screenshot with a little bit more context? I'm not seeing this issue immediately on my side. That being said, if the "Available Analysis" section is pulled up to the top, making the "Opened Traces" section have some overflow, then it will show the scroll bars:

image

Not sure if this what you are seeing? I can't fully tell from your screenshot.

**Comment by MatthewKhouzam** [comment]
@danieltomasku can you please make an experiment with say 20 traces? It should appear very easily.

**Comment by danieltomasku** [comment]
@MatthewKhouzam ok thanks! I see what you're talking about now. I just checked and this is the same behavior as what is on `master` currently. Looks like the row height is hardcoded at `50` (both on `master` and this commit):

master:
https://github.com/theia-ide/theia-trace-extension/blob/3908ad2aef7a86ca20a0348a41045ed5801bfbf7/viewer-prototype/src/browser/trace-explorer/trace-explorer-widget.tsx#L148-L155

this commit:
https://github.com/kenneth-marut-work/theia-trace-extension/blob/panelize-explorer/viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/trace-explorer-opened-traces-widget.tsx#L113-L118

we should probably make this dynamic. thoughts on how to resolve @kenneth-marut-work ?

**Comment by MatthewKhouzam** [comment]
@danieltomasku just for giggles, I typically have 2 user space traces and one kernel traces when I do personal tracing.

1- kernel
2- the game... er... application server
3- the server the .... application connects to. 

if more applications connect to said server, it can go up, but I would assume at least 3 for now. :)

**Comment by kenneth-marut-work** [comment]
@danieltomasku @MatthewKhouzam 
Thanks for pointing this out, and also good to hear it's not a regression 😉. I had come across that hard coded value during this refactor. I'll play around with it and see if I can get it to be a little bit more responsive 👌

**Comment by MatthewKhouzam** [comment]
OK, it "works" but I get residual issues.
image
btw, this new version looks amazing IMO except for the scroll bar.

**Comment by kenneth-marut-work** [comment]
@danieltomasku or @mirsky-work could either of you verify when you have a chance? I am not seeing the scrollbars that @MatthewKhouzam mentioned. He is running in firefox 84.0.2. I've changed my machine to that version and still not seeing scrollbars. I've tested in electron, chrome, and firefox on both Ubuntu VM and E2C environment.

Thanks 👍

**Comment by mirsky-work** [comment]
> @danieltomasku or @mirsky-work could either of you verify when you have a chance? I am not seeing the scrollbars that @MatthewKhouzam mentioned. He is running in firefox 84.0.2. I've changed my machine to that version and still not seeing scrollbars. I've tested in electron, chrome, and firefox on both Ubuntu VM and E2C environment.
> 
> Thanks 👍

I don't see that issue running in Gitpod on Chrome 87.0.4280.141, LGTM.

**Comment by danieltomasku** [comment]
I tested again and I'm not seeing the scrollbar issue in Chrome 87.0.4280.141 or Firefox 84.0.2

**Review by MatthewKhouzam — APPROVED** [review]
I am OK with this, let's get another reviewer up here though.

**Review by bhufmann — CHANGES_REQUESTED** [review]
Really great improvement. Thank you very much for this contribution! I was so close to approve and merge it, but then I noticed 3 things. 

The first one causes a TypeError (see inline comment to file trace-explorer-analysis-widget.tsx). 

The second one is when closing the Trace Explorer and reopening it. The "Open Trace" button is not shown anymore. This is a new behavior.
trace-explorer

The third one, the "Open Trace" command (type "CTRL+SHIFT+P" and then "Open Trace") is not there anymore.

Could you please fix this 3 findings?

**Review by kenneth-marut-work — COMMENTED** [review]
@bhufmann thank you for taking a thorough look and for catching those issues. Your comments had revealed some interesting behavior with the lifecycle management between the Viewer|Explorer, which have been resolved by these latest changes (thanks @colin-grant-work for your help debugging)

Regarding the above comments:

> The first one causes a TypeError (see inline comment to file trace-explorer-analysis-widget.tsx).

I have addressed this issue, I am no longer seeing this error when the last widget is closed. Note that I have been seeing this error occasionally when the last widget is closed, but have confirmed this exists on master as well:

image


> The second one is when closing the Trace Explorer and reopening it. The "Open Trace" button is not shown anymore. This is a new behavior.

This issue has been addressed. The widget will restore the placeholder view after closing and reopening when no Viewers are open.

> The third one, the "Open Trace" command (type "CTRL+SHIFT+P" and then "Open Trace") is not there anymore.

I had renamed the command label to 'Trace Viewer' intending to fix the `Open with -> Trace Viewer` wording, which had the unintended consequence of also renaming the command palette command. I have fixed both of issues, you should be able to access the command 'Open trace' even when the widget is closed.

Please let me know if you discover any other issues

**Review by bhufmann — APPROVED** [review]
I verified that my previous findings have been addressed. It looks good to me. Thanks for the contribution.

**Comment by kenneth-marut-work** [comment]
@bhufmann thanks for taking a look. I've just rebased to resolve conflicts 👌

**Pull request merged**
