### PR TITLE
Make chart background color darker (dark theme)

### PR DESCRIPTION
**Pull request by thefinaljob**
Changed the code to make the background color darker for the chart. It is now a shade of dark blue.

Contributes towards fixing #282

### CODE REVIEW

**Review by MatthewKhouzam — CHANGES_REQUESTED** [review]
Hi thefinaljob, 

thanks for the patch!

The commit message is kind of unclear. this changes the background color in light and dark theme
Light theme passes from https://duckduckgo.com/?q=color+picker+%23f4f7fb&ia=answer to https://duckduckgo.com/?q=color+picker+%23333f52&ia=answer

I find this _not pretty_. Maybe just change the dark one?

**Comment by MatthewKhouzam** [comment]
Here's a quick helper for commit messages.

https://www.freecodecamp.org/news/writing-good-commit-messages-a-practical-guide/

I am not always the best citizen on that front though.

Could look like this
----

Capitalized, short (50 chars or less) summary

More detailed explanatory text, if necessary.  Wrap it to about 72
characters or so.  In some contexts, the first line is treated as the
subject of an email and the rest of the text as the body.  The blank
line separating the summary from the body is critical (unless you omit
the body entirely); tools like rebase can get confused if you run the
two together.

Write your commit message in the imperative: "Fix bug" and not "Fixed bug"
or "Fixes bug."  This convention matches up with commit messages generated
by commands like git merge and git revert.

Further paragraphs come after blank lines.

- Bullet points are okay, too

- Typically a hyphen or asterisk is used for the bullet, followed by a
  single space, with blank lines in between, but conventions vary here

- Use a hanging indent

If you use an issue tracker, add a reference(s) to them at the bottom,
like so:

Resolves: #123

**Review by ebugden — CHANGES_REQUESTED** [review]
Requested changes 🌿

- [ ] **Include the issue that this contributes towards fixing** (#282) in the commit message and PR description
- [x] **For light theme: Change colour back to the the original theme background.** The contrast was already good and low in the light theme before this proposed patch.
- [x] **For dark theme: Change colour to a neutral grey that is slightly lighter than the tab background** (ex. #232323) (neutral grey: same values for red, green and blue). The tab background and the rest of the greys in the UI are often neutral. The chart background should be a shade of the tab background colour (same hue/saturation just different brightness)

If you want more details, you can check out the issue description #282. I just made some additions to clarify the requirements/motivation for the change. 

**The main goal of these changes is to decrease the contrast between the tab background and chart background.** If you convert the colours to HSB you can see that the colour proposed in this PR has a higher difference in brightness with the tab background than the original grey (i.e. the colour proposed here increases the contrast rather than decreasing it).

| Current background | Currently proposed background |
|-------------------|--------------------------|
| **Difference in Brightness (HSB):** ~13 image|**Difference in Brightness (HSB):** ~20 (higher contrast with tab background than original grey) image |
| **Chart background:** #3f3f3f image **Tab background:** #1e1e1e image  | **Chart background:** #333f52 image **Tab background:** #1e1e1e image  |

----

Light theme should look like this:
image

**Comment by MatthewKhouzam** [comment]
@ebugden Could you illustrate that with light theme too? my main issue is that it looks bad with light theme.

**Comment by MatthewKhouzam** [comment]
image
Here's what it looks like in light theme.

**Comment by ebugden** [comment]
@MatthewKhouzam I clarified my change requests. I'm aiming for something like this for light and dark themes: 
| Current Light Theme  | Proposed Adjusted Dark Theme |
|-------------------|--------------------------|
| **Difference in brightness (HSB):** ~2 image | **Difference in brightness (HSB):** ~2 image |
| Background: #ffffff image Chart background: #f4f7fb image | **Chart background:** #232323 image **Tab background:** #1e1e1e image |

**Review by ebugden — CHANGES_REQUESTED** [review]
Requested changes:

- [ ] **Update chartBackgroundColor in updateBackgroundTheme( )** as well. Right now when you switch to light theme and back to dark, it changes back to the light grey (see video below).
- [x] **Include the issue that this contributes towards fixing** (#282) in the commit message and PR description. This PR doesn't make the filter field darker so the issue shouldn't be closed when this PR is merged.
- [x] **Write commit title in imperative:** "Make chart background color darker"
- [ ] **Add signoff** to commit
- [ ] **Apply corrections by amending and force pushing the original commit** instead of creating a new one. There should be just one commit in the PR. (Let me know if you want some help doing this!) 

Thanks for updating the background colour! 🌼 I find this darker background to be less distracting.
 
| Current background | 🌈 PR Proposed background |
|--------------------------|---|
| image                    | image  |

----

Currently the chart background was only updated in the constructor not in updateBackgroundTheme( ). So when you switch to light theme and back to dark theme the colour is still the light grey (see 0:37 in the video):

https://user-images.githubusercontent.com/28311615/126551405-c2b2efa5-5226-4650-a8ec-84c930ed1c70.mp4

**Review by MatthewKhouzam — CHANGES_REQUESTED** [review]
please squash the two patches... we can't have both merged. ;)

**Comment by MatthewKhouzam** [comment]
Hi... er... I think you passed from 2 patches to 0 patches. How is this PR empty. I'm confused.

**Review by MatthewKhouzam — DISMISSED** [review]
WHooooooooooooo!

**Review by MatthewKhouzam — APPROVED** [review]
Wasn't there a light theme change too? I guess this is OK.

**Comment by ebugden** [comment]
> Wasn't there a light theme change too? I guess this is OK.

No the light theme was good already. The goal of this change was to have lower contrast between the tab background and chart background in the dark theme (similar to the low contrast already in the light theme) (See #282).

**Review by ebugden — CHANGES_REQUESTED** [review]
- [x] Reference the issue #282 in the commit message (instead of the PR #382) 🍰

One last change!

**Review by ebugden — APPROVED** [review]
Looks good to me! 🌵 @thefinaljob We can merge after approval from a second committer. I just sent the additional review request so it can take a little while.

**Review by bhufmann — APPROVED** [review]
Looks good to me. Thanks!

**Review by IbrahimFradj — APPROVED** [review]
Looks good to me, thank you.

**Pull request merged**
