### PR TITLE
Use plugin per chart instance instead of global for time selection

### LINKED ISSUE #269: Time selection not cleared when closing xy chart
The time selection in an xy-chart is not cleared when closing the chart. This can be observed when re-opening the xy-chart after the time selecting was change while the xy-chart was closed.

bug-xy-chart-selection

### PR DESCRIPTION
**Pull request by bhufmann**
Fixes #269

Signed-off-by: Bernd Hufmann <Bernd.Hufmann@ericsson.com>

### CODE REVIEW

**Review by PatrickTasse — CHANGES_REQUESTED** [review]
When there is a selection range but no checked element in the XY tree, it appears that the XY chart is completely filled by a blue selection rectangle.

**Comment by PatrickTasse** [comment]
> When there is a selection range but no checked element in the XY tree, it appears that the XY chart is completely filled by a blue selection rectangle.

Sorry, this behaviour exists before this patch.

**Comment by bhufmann** [comment]
> > When there is a selection range but no checked element in the XY tree, it appears that the XY chart is completely filled by a blue selection rectangle.
> 
> Sorry, this behaviour exists before this patch.

No problem. I think this should be fixed in a separate patch.

**Review by PatrickTasse — APPROVED** [review]

**Review by MatthewKhouzam — APPROVED** [review]
I confirm, it fixes the bug.

**Pull request merged**
