### PR TITLE
Make the quick start work on windows

### PR DESCRIPTION
**Pull request by arfio**
Use the shx library to make cp and mkdir command work under windows
terminal.

Signed-off-by: Arnaud Fiorini <fiorini.arnaud@gmail.com>

### CODE REVIEW

**Review by bhufmann — APPROVED** [review]
Looks good to me and still works in Linux. Don't have a way to check Windows though.

**Comment by bhufmann** [comment]
@arfio Sorry, #205 was just merged. Your patch has some merge conflicts. Could you please resolve them? I think there are new "mkdir" commands added in one or more package.json file. If true, could you please update them too?

**Comment by arfio** [comment]
@bhufmann This merge request is no longer useful, the mkdir and copy commands have been removed from the scripts with the #205. Now the build works without the need of the shx package.

Also, building on Windows for this package is not needed for now, because of the following issue with Theia: https://github.com/eclipse-theia/theia/issues/8098.

**Comment by bhufmann** [comment]
> @bhufmann This merge request is no longer useful, the mkdir and copy commands have been removed from the scripts with the #205. Now the build works without the need of the shx package. I'm not sure where the "mkdir" commands have been added but the options used must be compatible with the windows alias.
> 
> Also, building on Windows for the theia-trace-extension is not needed for now, because of the following issue with Theia: [eclipse-theia/theia#8098](https://github.com/eclipse-theia/theia/issues/8098).

Thanks for letting me know.

**Pull request closed without merging**
